### ISSUE TITLE
项目后期任务

### ISSUE THREAD

**Issue by Hughshine** [Hughshine/nm_ticketing_api#3]
- [x] frontend\backend功能实现
- [x] rules调整
- [x] save(false) 等不安全代码处理，优化代码结构 
- [x] 数据库文件更新

部署任务：
- [ ] 域名、https认证

其他：
- [x] 登录时验证来源为小程序

**Comment by Hughshine** [comment]
- [ ] 完成后给仓库改一个名字。

**Comment by LYL232** [comment]
- [ ] logged_at字段问题,先删除各个用户表中的logged_at相关内容,如要实现以后可以新开一个表

- [ ] 尽量做到IDE里没有警告,处理所有能被抛出的异常

- [ ] 找回密码:

- [ ] 小程序端找回

- [ ] 网页端邮箱找回

**Comment by Hughshine** [comment]
另起一个新的issue。
